
CONDA_PATH=`which activate`
source ${CONDA_PATH} oob_tf_utb
which python

model_path=(
## Q3-2020
/home2/tensorflow-broad-product/oob_tf_models/mlp/HugeCTR/HugeCTR.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/action_recognition/i3d/flow/tf/i3d-flow.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/action_recognition/i3d/rgb/tf/i3d-rgb.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/densenet/121/tf/densenet-121.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/densenet/161/tf/densenet-161.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/densenet/169/tf/densenet-169.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/googlenet/v1/tf/googlenet-v1.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/googlenet/v2/tf/googlenet-v2.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/googlenet/v3/tf/googlenet-v3.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/googlenet/v4/tf/googlenet-v4.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/image-retrieval-0001/image-retrieval-0001.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/inception-resnet/v2/tf/inception-resnet-v2.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/nasnet/large/tf/nasnet-a-large-331.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/nasnet/mobile/tf/nasnet-a-mobile-224.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/resnet/v1/101/tf/resnet-101.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/resnet/v1/152/tf/resnet-152.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/resnet/v1/50/tf/official/resnet-50.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/resnet/v2/101/tf/resnet-v2-101.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/resnet/v2/152/tf/resnet-v2-152.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/resnet/v2/50/tf/224x224/resnet-v2-50.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/squeezenet/1.1/tf/squeezenet1_1.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/vgg/16/tf/vgg16.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/vgg/19/tf/vgg19.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/human_pose_estimation/3d-pose-baseline/tf/3d-pose-baseline.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/human_pose_estimation/cpm/person/tf/cpm-person.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/human_pose_estimation/openpose/pose/tf/openpose-pose.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/instance_segmentation/mask_rcnn/mask_rcnn_inception_v2_coco/tf/mask_rcnn_inception_v2_coco.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/IntelLabs/FastImageProcessing/NonlocalDehazing/intel-labs-nonlocal-dehazing.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/IntelLabs/LearningToSeeInTheDark/Fuji/learning-to-see-in-the-dark-fuji.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/IntelLabs/LearningToSeeInTheDark/Sony/learning-to-see-in-the-dark-sony.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/language_representation/bert/base/uncased_L-12_H-768_A-12/tf/bert-base-uncased_L-12_H-768_A-12.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/object_attributes/vehicle_attributes/tf/vehicle-attributes-barrier-0103.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/object_detection/barrier/tf/0123/vehicle-license-plate-detection-barrier-0123.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/object_detection/common/faster_rcnn/faster_rcnn_inception_v2_coco/tf/faster_rcnn_inception_v2_coco.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/object_detection/common/faster_rcnn/faster_rcnn_resnet101_coco/tf/faster_rcnn_resnet101_coco.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/object_detection/common/faster_rcnn/faster_rcnn_resnet50_coco/tf/faster_rcnn_resnet50_coco.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/object_detection/common/faster_rcnn/faster_rcnn_resnet50_lowproposals_coco/tf/faster_rcnn_resnet50_lowproposals_coco.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/object_detection/common/retinanet/tf/retinanet.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/object_detection/common/rfcn/rfcn_resnet101_coco/tf/rfcn-resnet101-coco.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/object_detection/common/ssd_inceptionv2/tf/inceptionv2_ssd.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/object_detection/common/ssd_resnet50/ssd_resnet50_v1_fpn_coco/tf/ssd_resnet50_v1_fpn_coco.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/object_detection/yolo/yolo_v2/tf/yolo-v2.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/object_detection/yolo/yolo_v3/tf/yolo-v3.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/PublicCompressed/detection/tinyYOLOv2/fp32_sparsity00/yolo-v2-tiny-ava-0001.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/PublicCompressed/detection/tinyYOLOv2/fp32_sparsity30/yolo-v2-tiny-ava-sparse-30-0001.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/PublicCompressed/detection/tinyYOLOv2/fp32_sparsity60/yolo-v2-tiny-ava-sparse-60-0001.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/PublicCompressed/detection/YOLOv2/fp32_sparsity35/yolo-v2-ava-sparse-35-0001.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/PublicCompressed/detection/YOLOv2/fp32_sparsity70/yolo-v2-ava-sparse-70-0001.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/PublicCompressed/semantic_segmentation/icnet-camvid-tf-ws00/icnet-camvid-ava-0001.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/PublicCompressed/semantic_segmentation/icnet-camvid-tf-ws30/icnet-camvid-ava-sparse-30-0001.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/PublicCompressed/semantic_segmentation/icnet-camvid-tf-ws60/icnet-camvid-ava-sparse-60-0001.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/PublicInHouse/classification/darknet19/darknet19.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/PublicInHouse/classification/darknet53/darknet53.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/PublicInHouse/object_detection/common/dssd/DSSD_12/tf/DSSD_12.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/PublicInHouse/object_detection/common/yolo/v1_tiny/tf/tiny_yolo_v1.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/PublicInHouse/object_detection/common/yolo/v2_tiny/tf/tiny_yolo_v2.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/PublicInHouse/sequence_modelling/tcn/tf/TCN.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/Retail/action_detection/pedestrian/rmnet_ssd/0028_tf/tf/rmnet_ssd.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/Retail/object_attributes/emotions_recognition/0002/tf/icv-emotions-recognition-0002.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/Security/feature_extraction/ava/tf/ava-face-recognition-3.0.0.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/Security/object_detection/barrier/yolo/yolo-v2-tiny-vehicle-detection-0001/tf/yolo-v2-tiny-vehicle-detection-0001.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/Security/object_detection/common/ava/stage2/tf/ava-person-vehicle-detection-stage2-2.0.0.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/Security/object_detection/crossroad/1020/tf/person-vehicle-bike-detection-crossroad-yolov3-1020.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/semantic_segmentation/deeplab/v3/deeplabv3.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/text_detection/ctpn/tf/ctpn.pb
/home2/tensorflow-broad-product/oob_tf_models/ckpt/faster_rcnn_resnet101_fgvc_2018_07_19/faster_rcnn_resnet101_fgvc_2018_07_19/faster_rcnn_resnet101_fgvc.pb
/home2/tensorflow-broad-product/oob_tf_models/ckpt/faster_rcnn_resnet101_kitti_2018_01_28/faster_rcnn_resnet101_kitti_2018_01_28/faster_rcnn_resnet101_kitti.pb
/home2/tensorflow-broad-product/oob_tf_models/ckpt/faster_rcnn_resnet101_lowproposals_coco_2018_01_28/faster_rcnn_resnet101_lowproposals_coco_2018_01_28/faster_rcnn_resnet101_lowproposals_coco.pb
/home2/tensorflow-broad-product/oob_tf_models/ckpt/faster_rcnn_resnet50_fgvc_2018_07_19/faster_rcnn_resnet50_fgvc_2018_07_19/faster_rcnn_resnet50_fgvc.pb
/home2/tensorflow-broad-product/oob_tf_models/ckpt/ssd_inception_v2_coco_2018_01_28/ssd_inception_v2_coco_2018_01_28/ssd_inception_v2_coco.pb
/home2/tensorflow-broad-product/oob_tf_models/ckpt/ssd-resnet34_300x300/ssd_resnet34_300x300.pb
/home2/tensorflow-broad-product/oob_tf_models/mlp/deeplabv3_mnv2_cityscapes_train/deeplab.pb
/home2/tensorflow-broad-product/oob_tf_models/ckpt/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03/SSD_ResNet50_V1_FPN_640x640_RetinaNet50.pb
/home2/tensorflow-broad-product/oob_tf_models/dpg/DRAW/DRAW.pb
/home2/tensorflow-broad-product/oob_tf_models/mlp/vnet/vnet.pb
/home2/tensorflow-broad-product/oob_tf_models/mlp/GraphSage/GraphSage.pb
/home2/tensorflow-broad-product/oob_tf_models/mlp/oob_gan_models/WGAN.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/efficientnet/b0/tf/efficientnet-b0.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/efficientnet/b0_auto_aug/tf/efficientnet-b0_auto_aug.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/efficientnet/b5/tf/efficientnet-b5.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/classification/efficientnet/b7_auto_aug/tf/efficientnet-b7_auto_aug.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/voice_recognition/vggvox/vggvox.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/AIPG_trained/text_classification/vdcnn/agnews/tf/aipg-vdcnn.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/human_pose_estimation/arttrack/coco/tf/arttrack-coco-multi.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/human_pose_estimation/arttrack/mpii/tf/arttrack-mpii-single.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/dna_sequencing/deepvariant/wgs/deepvariant_wgs.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/text_detection/east/tf/east_resnet_v1_50.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/face_recognition/facenet/CASIA-WebFace/tf/facenet-20180408-102900.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/Retail/handwritten-score-recognition/0003/tf/handwritten-score-recognition-0003.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/optical_character_recognition/license_plate_recognition/tf/license-plate-recognition-barrier-0007.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/optical_character_recognition/text_recognition/tf/optical_character_recognition-text_recognition-tf.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/face_reconstruction/PRNet/tf/PRNet.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/Retail/text_recognition/bilstm_crnn_bilstm_decoder/0012/tf/text-recognition-0012.pb
/home2/tensorflow-broad-product/oob_tf_models/dpg/Hierarchical/Hierarchical_LSTM.pb
/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/object_detection/yolo/yolo_v3/yolo-v3-tiny/yolo-v3-tiny-tf/yolo-v3-tiny.pb
/home2/tensorflow-broad-product/oob_tf_models/dpg/Resnet_v2_200/resnet_v2_200.pb
## Q4-2020
#/home2/tensorflow-broad-product/oob_tf_models/mlp/CBAM/CBAM.pb
#/home2/tensorflow-broad-product/oob_tf_models/dpg/ALBERT/ALBERT.pb
#/home2/tensorflow-broad-product/oob_tf_models/mlp/BERT_BASE/BERT_BASE.pb
#/home2/tensorflow-broad-product/oob_tf_models/mlp/BERT_LARGE/BERT_LARGE.pb
#/home2/tensorflow-broad-product/oob_tf_models/dpg/CharCNN/CharCNN.pb
#/home2/tensorflow-broad-product/oob_tf_models/ov/Dilation/dilation.pb
#/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/object_detection/common/faster_rcnn/faster_rcnn_inception_resnet_v2_atrous_coco/tf/faster_rcnn_inception_resnet_v2_atrous_coco.pb
#/home2/tensorflow-broad-product/oob_tf_models/ckpt/faster_rcnn_inception_resnet_v2_atrous_lowproposals_coco_2018_01_28/faster_rcnn_inception_resnet_v2_atrous_lowproposals_coco.pb
#/home2/tensorflow-broad-product/oob_tf_models/ckpt/faster_rcnn_nas_coco_2018_01_28/faster_rcnn_nas_coco_2018_01_28.pb
#/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/object_detection/common/faster_rcnn/faster_rcnn_nas_lowproposals_coco/tf/faster_rcnn_nas_lowproposals_coco.pb
#/home2/tensorflow-broad-product/oob_tf_models/mlp/oob_gan_models/GAN.pb
#/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/image_inpainting/gmcnn/tf/gmcnn-places2.pb
#/home2/tensorflow-broad-product/oob_tf_models/mlp/oob_gan_models/LSGAN.pb
#/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/instance_segmentation/mask_rcnn/mask_rcnn_inception_resnet_v2_atrous_coco/tf/mask_rcnn_inception_resnet_v2_atrous_coco.pb
#/home2/tensorflow-broad-product/oob_tf_models/dpg/ncf_trained_movielens_1m/NCF-1B.pb
#/home2/tensorflow-broad-product/oob_tf_models/dpg/R-FCN/rfcn_resnet101_coco_2018_01_28/R-FCN.pb
#/home2/tensorflow-broad-product/oob_tf_models/mlp/transformer_lt_official_fp32_pretrained_model/graph/Transformer-LT.pb
#/home2/tensorflow-broad-product/oob_tf_models/oob/checkpoint_dynamic_memory_network/DynamicMemory.pb
#/home2/tensorflow-broad-product/oob_tf_models/oob/checkpoint_entity_network2/EntityNet.pb
#/home2/tensorflow-broad-product/oob_tf_models/oob/Seq2seqAttn/Seq2seqAttn.pb
#/home2/tensorflow-broad-product/oob_tf_models/mlp/SqueezeNet-tf/SqueezeNet.pb
#/home2/tensorflow-broad-product/oob_tf_models/mlp/ssd_resnet34_model/ssd_resnet34_1200x1200.pb
#/home2/tensorflow-broad-product/oob_tf_models/oob/TextRCNN/TextRCNN.pb
#/home2/tensorflow-broad-product/oob_tf_models/mlp/unet/U-Net.pb
#/home2/tensorflow-broad-product/oob_tf_models/dpg/wavenet/wavenet.pb
#/home2/tensorflow-broad-product/oob_tf_models/dpg/SphereFace/SphereFace.pb
#/home2/tensorflow-broad-product/oob_tf_models/oob/checkpoint_hier_atten_title/text_hier_atten_title_desc_checkpoint_MHA/HierAtteNet.pb
#/home2/tensorflow-broad-product/oob_tf_models/mlp/ResNet50_v1_5/model_dir/ResNet-50_v1.5.pb
#/home2/tensorflow-broad-product/oob_tf_models/dpg/ResNext_50/ResNext_50.pb
#/home2/tensorflow-broad-product/oob_tf_models/dpg/ResNext_101/ResNext_101.pb
#/home2/tensorflow-broad-product/oob_tf_models/oob/COVID-Net/COVID-Net.pb
#/home2/tensorflow-broad-product/oob_tf_models/mlp/CRNN/crnn.pb
#/home2/tensorflow-broad-product/oob_tf_models/mlp/CenterNet/CenterNet.pb
#/home2/tensorflow-broad-product/oob_tf_models/dpg/CapsuleNet/CapsuleNet.pb
#/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/speech_to_text/deepspeech/v1/tf/deepspeech.pb
#/home2/tensorflow-broad-product/oob_tf_models/oob/DIEN/DIEN.pb
#/home2/tensorflow-broad-product/oob_tf_models/ov/all_tf_models/semantic_segmentation/dense_vnet/tf/dense_vnet_abdominal_ct.pb
#/home2/tensorflow-broad-product/oob_tf_models/oob/TextCNN/TextCNN.pb
#/home2/tensorflow-broad-product/oob_tf_models/oob/TextRNN/TextRNN.pb
#/home2/tensorflow-broad-product/oob_tf_models/oob/show_and_tell/show_and_tell.pb
#/home2/tensorflow-broad-product/oob_tf_models/dpg/MiniGo/MiniGo.pb
)

for model in ${model_path[@]}
do
    ./launch_benchmark.sh --checkpoint=${model} --use_TF_NativeFormat=1 --run_perf=1 --collect_dnnl_verbose=1 --precision=bfloat16 
done

:<<EOF
for model in ${model_path[@]}
do
    ./launch_benchmark.sh --checkpoint=${model} --use_TF_NativeFormat=1 --run_perf=1 --collect_dnnl_verbose=1  --precision=bfloat32
done
EOF
